import generated from "../generated/panels.json";

export interface PanelDef {
  uid: string;
  dashboard: string;
  id: number;
  title: string;
  team_var: boolean;
}

/** Generated by observability/build_dashboards.py; a control-plane test keeps it in sync. */
export const PANELS: PanelDef[] = generated.panels;

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

/** The d-solo URL for one panel, or undefined when Grafana is off or the base is not http(s). */
export function panelUrl(base: string, p: PanelDef, opt: { theme: "light" | "dark"; team?: string }): string | undefined {
  let root: URL;
  try {
    root = new URL(base);
  } catch {
    return undefined;
  }
  if (root.protocol !== "http:" && root.protocol !== "https:") return undefined;
  const q = new URLSearchParams({ orgId: "1", panelId: String(p.id), theme: opt.theme, refresh: "5s", from: "now-30m", to: "now" });
  if (p.team_var) q.set("var-team", opt.team || "All");
  return `${root.origin}${root.pathname.replace(/\/$/, "")}/d-solo/${p.uid}/${slug(p.dashboard)}?${q}`;
}
